### ISSUE TITLE
Restore incoherent schema option

### ISSUE THREAD

**Issue by Simon3** [nuvo/cain#16]
Not sure if this is a bug or just me misunderstanding something. 
For the context, in my case, the backup will be created at path: gcs://<bucketName>/cassandra/cassandra/ozone_33_latest/df2f79/20190329085025

> cain restore --help
> -s, --schema string               schema version to restore (optional).

First thing, the "schema version" is actually the schemaHash output by the backup, e.g. df2f79, maybe it's a bit misleading in the above description. 

Secondly, the argument is optional, but if we don't specify it, it tries to restore a backup at path cassandra/cassandra/ozone_33_latest/ozone_33_latest/20190329085025, which doesn't exist. Maybe I missed something here?

**Comment by maorfr** [comment]
The schema version flag (yes, it is actually the hash of the schema, valid point) is optional and should be used if you want to restore the schema as well. If the schema already exists, this flag may be ommitted, as cain will check the schema before the restore.

What I am missing here is the keyspace. Is it really missing or am I missing something now? :)

**Comment by Simon3** [comment]
Ok it's actually my bad, but to be clearer, ozone_33_latest is both my keyspace and my schema name. 
I was trying to restore a backup with no local schema and without specifying the -s option. Which is not supported, I know. But the result was a bit ambiguous, since it seems like cain tried to "guess" the schema by using the same name as the keyspace. Which was correct! Except that it didn't hash it. Which is why it used ozone_33_latest/ozone_33_latest in the path, which doesn't really have any sense. 

In this case, I would expect cain to either: 
- fail with an explicit error, like "no schema found locally, please specify --schema option"
- guess the schema as being the same as the keyspace (current behaviour) + hash it

But yeah, it doesn't really matter.

**Comment by maorfr** [comment]
Your use case should have failed here:
https://github.com/nuvo/cain/blob/master/pkg/cain/cain.go#L118
Because this had returned an error:
https://github.com/nuvo/cain/blob/master/pkg/cain/cqlsh.go#L43

If it didn't, can you send more information?
The executed command, the output, ...

**Comment by Simon3** [comment]
Hmm it indeed does. I guess I messed up with the command the first time. So apart from the slightly misleading "schema version flag", there is actually no problem. Sorry!
