### ISSUE TITLE
Question about the life of cain project

### ISSUE THREAD

**Issue by ahmedjami** [nuvo/cain#21]
Hi,
I'm about testing Cassandra deployment on K8S and I found your project for backup/restore data.

Considering the date of last commit, I'm wondering if your interesting project is still maintained? If it's not, could you advise me if there is another solution for backup cassandra data on k8s.

Thanks a lot.

**Comment by maorfr** [comment]
checkout maorfr/cain

**Comment by ahmedjami** [comment]
thanks a lot @maorfr 
I have another question please, Do you use  cain on prod ? It works fine ? 
What about update ? The current repo work fine with tle latest version of K8S, Go ... ?

Thanks :)

**Comment by maorfr** [comment]
It's used as the backup tool for the Cassandra Helm chart, and I haven't heard complaints, if that answers your question.

**Comment by ahmedjami** [comment]
Thanks a lot @maorfr 
I'll test it :)
