### ISSUE TITLE
Data Dir Does Not Exist!!

### ISSUE THREAD

**Issue by AkashRajvanshi** [nuvo/cain#27]
Hey, I am using bitnami cassandra chart for my deployment & I want to use cain for backup my keyspaces to s3. In bitnami Cassandra image data dir is `/bitnami/cassandra/data/data/keyspaces`. How should I change data dir in cain??

```bash
kubectl logs -f pod/cassandra-backup-system-1614667800-sl6pc                                        
2021/03/02 06:50:26 Backup started!
2021/03/02 06:50:26 Getting clients
2021/03/02 06:50:26 Getting pods
2021/03/02 06:50:26 Testing existence of data dir
2021/03/02 06:50:26 /var/lib/cassandra/data does not exist. error in Stream: command terminated with exit code 2
```

**Comment by maorfr** [comment]
i believe you should use `--cassandra-data-dir`? (was added in #9)

**Comment by AkashRajvanshi** [comment]
thank you :)
